#!/usr/bin/env python3
"""Generate or check a deterministic research-journal retrieval index."""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

from relationship_reviews import LedgerError, RelationshipReviews


SCHEMA_VERSION = 3
INDEX_NAME = "INDEX.md"
HEADER_RE = re.compile(
    r"\A<!-- GENERATED by .*?; DO NOT EDIT\.\n"
    r"schema: (?P<schema>\d+)\n"
    r"source-sha256: (?P<digest>[0-9a-f]{64})\n"
    r"-->\n",
    re.DOTALL,
)
TYPE_ORDER = ("studies", "learnings", "questions", "decisions", "meetings", "sessions", "experiments")
TYPE_HEADINGS = {
    "studies": "Research studies",
    "learnings": "Durable learnings",
    "questions": "Research questions",
    "decisions": "Decisions",
    "meetings": "Meetings",
    "sessions": "Research sessions",
    "experiments": "Experiment cards",
}
SUMMARY_HEADINGS = {
    "studies": ("Objective", "Research questions", "Design commitments"),
    "learnings": ("Claim",),
    "questions": ("Question", "Why it matters"),
    "decisions": ("Decision",),
    "meetings": ("Summary", "Notes"),
    "sessions": ("Intent", "Outcome", "Running notes"),
    "experiments": (
        "Question",
        "What this experiment is trying to do",
        "Interpretation",
        "Results",
    ),
}
STATUS_PRIORITY = {
    "in-progress": 0,
    "running": 0,
    "active": 0,
    "supported": 0,
    "open": 1,
    "planned": 1,
    "tentative": 1,
    "blocked": 2,
    "partial": 2,
    "done": 3,
    "answered": 3,
    "contradicted": 4,
    "abandoned": 4,
    "obsolete": 5,
    "superseded": 6,
}


@dataclass(frozen=True)
class Entry:
    note_type: str
    path: Path
    title: str
    status: str
    date: str
    summary: str


@dataclass(frozen=True)
class Inspection:
    state: str
    path: Path
    expected_digest: str
    actual_digest: str | None
    expected_text: str


def parse_frontmatter(text: str) -> dict[str, str]:
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    result: dict[str, str] = {}
    for line in lines[1:]:
        if line.strip() == "---":
            return result
        if not line.strip() or line.lstrip().startswith("#") or ":" not in line:
            continue
        key, value = line.split(":", 1)
        result[key.strip()] = value.strip().strip("\"'")
    return {}


def field(text: str, name: str) -> str | None:
    match = re.search(rf"(?m)^{re.escape(name)}:\s*(.+?)\s*$", text)
    return match.group(1).strip() if match else None


def section_lines(text: str, name: str) -> list[str] | None:
    heading = f"## {name}"
    lines = text.splitlines()
    try:
        start = next(index for index, line in enumerate(lines) if line.strip() == heading) + 1
    except StopIteration:
        return None
    result: list[str] = []
    for line in lines[start:]:
        match = re.match(r"^(#+)\s", line)
        if match and len(match.group(1)) <= 2:
            break
        result.append(line)
    return result


def first_paragraph(lines: list[str] | None) -> str | None:
    if lines is None:
        return None
    paragraph: list[str] = []
    in_comment = False
    for raw in lines:
        line = raw.strip()
        if line.startswith("<!--"):
            in_comment = True
        if in_comment:
            if "-->" in line:
                in_comment = False
            continue
        if not line:
            if paragraph:
                break
            continue
        if line.startswith("#"):
            if paragraph:
                break
            continue
        paragraph.append(re.sub(r"^[-*]\s+", "", line))
    return " ".join(paragraph) if paragraph else None


def title(text: str, fallback: str) -> str:
    match = re.search(r"(?m)^#\s+(.+?)\s*$", text)
    return match.group(1).strip() if match else fallback


def shorten(text: str, limit: int = 240) -> str:
    normalized = re.sub(r"\s+", " ", text).strip()
    if len(normalized) <= limit:
        return normalized
    candidate = normalized[: limit - 1].rsplit(" ", 1)[0]
    return (candidate or normalized[: limit - 1]).rstrip() + "…"


def markdown_cell(text: str) -> str:
    return text.replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ").strip()


def link_target(index_path: Path, target: Path) -> str:
    relative = os.path.relpath(target, index_path.parent).replace(os.sep, "/")
    return relative.replace(" ", "%20")


class JournalIndex:
    def __init__(
        self,
        root: Path,
        notebook: str = "lab-notebook",
        experiments: str = "experiments/*",
        sessions: str | None = None,
    ) -> None:
        self.root = root.resolve()
        self.notebook = (self.root / notebook).resolve()
        self.experiments_glob = experiments
        self.sessions = (self.root / (sessions or f"{notebook}/sessions")).resolve()
        self.path = self.notebook / INDEX_NAME

    def source_files(self) -> list[tuple[str, Path]]:
        sources: list[tuple[str, Path]] = []
        studies = self.notebook / "studies"
        if studies.is_dir():
            sources.extend(("studies", path) for path in sorted(studies.glob("*.md")) if path.is_file())
        for note_type in ("learnings", "questions", "decisions", "meetings"):
            directory = self.notebook / "notes" / note_type
            if not directory.is_dir():
                continue
            sources.extend(
                (note_type, path)
                for path in sorted(directory.glob("*.md"))
                if path.is_file() and path.name != "README.md"
            )
        if self.sessions.is_dir():
            sources.extend(("sessions", path) for path in sorted(self.sessions.glob("*.md")) if path.is_file())
        sources.extend(
            ("experiments", directory / "README.md")
            for directory in sorted(path for path in self.root.glob(self.experiments_glob) if path.is_dir())
            if (directory / "README.md").is_file()
        )
        return sources

    def digest(self, sources: list[tuple[str, Path]] | None = None) -> str:
        hasher = hashlib.sha256()
        paths = [path for _, path in (sources or self.source_files())]
        ledger = self.notebook / "relationship-reviews.jsonl"
        if ledger.is_file():
            paths.append(ledger)
        for path in paths:
            try:
                relative = path.resolve().relative_to(self.root).as_posix()
            except ValueError:
                relative = path.resolve().as_posix()
            hasher.update(relative.encode("utf-8"))
            hasher.update(b"\0")
            hasher.update(path.read_bytes())
            hasher.update(b"\0")
        return hasher.hexdigest()

    def entry(self, note_type: str, path: Path) -> Entry:
        text = path.read_text(encoding="utf-8")
        meta = parse_frontmatter(text)
        status = meta.get("status") or field(text, "Status") or "unknown"
        item_date = (
            meta.get("updated")
            or meta.get("created")
            or field(text, "Date")
            or field(text, "Created")
            or "unknown"
        )
        summary = None
        for heading in SUMMARY_HEADINGS[note_type]:
            summary = first_paragraph(section_lines(text, heading))
            if summary:
                break
        return Entry(
            note_type=note_type,
            path=path,
            title=title(text, path.stem),
            status=status,
            date=item_date,
            summary=shorten(summary or "No indexed summary."),
        )

    def entries(self, sources: list[tuple[str, Path]] | None = None) -> list[Entry]:
        return [self.entry(note_type, path) for note_type, path in sources or self.source_files()]

    @staticmethod
    def sort_key(entry: Entry) -> tuple[int, int, str]:
        date_number = int(entry.date.replace("-", "")) if re.fullmatch(r"\d{4}-\d{2}-\d{2}", entry.date) else 0
        return STATUS_PRIORITY.get(entry.status, 50), -date_number, entry.path.as_posix()

    def render(self) -> tuple[str, str]:
        sources = self.source_files()
        digest = self.digest(sources)
        try:
            tool_path = (self.notebook.relative_to(self.root) / "tools" / "index.py").as_posix()
        except ValueError:
            tool_path = "research-journal index.py"
        grouped: dict[str, list[Entry]] = {note_type: [] for note_type in TYPE_ORDER}
        for entry in self.entries(sources):
            grouped[entry.note_type].append(entry)
        lines = [
            f"<!-- GENERATED by {tool_path}; DO NOT EDIT.",
            f"schema: {SCHEMA_VERSION}",
            f"source-sha256: {digest}",
            "-->",
            "# Research index",
            "",
            "This is a generated retrieval map. Canonical content remains in the linked study cards, notes, sessions, and experiment cards.",
        ]
        try:
            maintenance = RelationshipReviews(self.root, self.notebook).status()
            notes, pairs = maintenance["notes"], maintenance["pairs"]
            last_audit = maintenance["last_audit"]
            verdicts = ", ".join(f"{name}: {count}" for name, count in pairs["by_verdict"].items()) or "none"
            lines.extend(
                [
                    "",
                    "## Relationship maintenance",
                    "",
                    f"- Current note audit coverage: {notes['current']}/{notes['total']}",
                    f"- Review debt: {notes['stale']} changed; {notes['unreviewed']} never audited",
                    f"- Pair decisions: {pairs['current']} current; {pairs['stale']} stale",
                    f"- Current verdicts: {verdicts}",
                    f"- Last note audit: {last_audit['timestamp']} by {last_audit['reviewer']}" if last_audit else "- Last note audit: none",
                ]
            )
        except LedgerError as error:
            lines.extend(["", "## Relationship maintenance", "", f"- Ledger error: {markdown_cell(str(error))}"])
        for note_type in TYPE_ORDER:
            lines.extend(["", f"## {TYPE_HEADINGS[note_type]}", ""])
            entries = sorted(grouped[note_type], key=self.sort_key)
            if not entries:
                lines.append("_None._")
                continue
            lines.extend(["| Status | Updated | Entry | Summary |", "|---|---|---|---|"])
            for entry in entries:
                label = markdown_cell(entry.title)
                target = link_target(self.path, entry.path)
                lines.append(
                    f"| {markdown_cell(entry.status)} | {markdown_cell(entry.date)} | "
                    f"[{label}]({target}) | {markdown_cell(entry.summary)} |"
                )
        return "\n".join(lines) + "\n", digest

    def inspect(self) -> Inspection:
        expected_text, expected_digest = self.render()
        if not self.path.is_file():
            return Inspection("missing", self.path, expected_digest, None, expected_text)
        try:
            actual_text = self.path.read_text(encoding="utf-8")
        except (OSError, UnicodeError):
            return Inspection("malformed", self.path, expected_digest, None, expected_text)
        match = HEADER_RE.match(actual_text)
        if not match or int(match.group("schema")) != SCHEMA_VERSION:
            return Inspection("malformed", self.path, expected_digest, None, expected_text)
        actual_digest = match.group("digest")
        state = "fresh" if actual_text == expected_text else "stale"
        return Inspection(state, self.path, expected_digest, actual_digest, expected_text)

    def write(self) -> bool:
        expected_text, _ = self.render()
        if self.path.is_file() and self.path.read_text(encoding="utf-8") == expected_text:
            return False
        self.path.parent.mkdir(parents=True, exist_ok=True)
        mode = self.path.stat().st_mode & 0o777 if self.path.exists() else 0o644
        temporary: str | None = None
        try:
            with tempfile.NamedTemporaryFile(
                "w",
                encoding="utf-8",
                dir=self.path.parent,
                prefix=f".{self.path.name}.",
                delete=False,
            ) as handle:
                handle.write(expected_text)
                temporary = handle.name
            os.chmod(temporary, mode)
            os.replace(temporary, self.path)
        finally:
            if temporary and os.path.exists(temporary):
                os.unlink(temporary)
        return True


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", default=".", help="project root (default: current directory)")
    parser.add_argument("--notebook", default="lab-notebook", help="notebook path relative to project")
    parser.add_argument("--experiments", default="experiments/*", help="experiment directory glob")
    parser.add_argument("--sessions", help="sessions path relative to project")
    action = parser.add_mutually_exclusive_group()
    action.add_argument("--write", action="store_true", help="atomically regenerate INDEX.md")
    action.add_argument("--stdout", action="store_true", help="emit a current index without writing")
    action.add_argument("--check", action="store_true", help="check index freshness without writing (default)")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    journal_index = JournalIndex(Path(args.project), args.notebook, args.experiments, args.sessions)
    if args.stdout:
        text, _ = journal_index.render()
        print(text, end="")
        return 0
    if args.write:
        changed = journal_index.write()
        print(f"{'Updated' if changed else 'Fresh'}: {journal_index.path}")
        return 0
    inspection = journal_index.inspect()
    print(f"{inspection.state.capitalize()}: {inspection.path}")
    if inspection.state == "stale":
        if inspection.actual_digest == inspection.expected_digest:
            print("The source digest is current, but the generated contents differ.")
        else:
            print(f"Expected source digest: {inspection.expected_digest}")
            print(f"Recorded source digest: {inspection.actual_digest}")
    return 0 if inspection.state == "fresh" else 1


if __name__ == "__main__":
    raise SystemExit(main())
